name: build

# TODO Add sanitizers via cmake parameters.

on:
  push:
    branches: [ develop, main ]

jobs:
  # Ubuntu-20 GCC
  gcc-build-ubuntu20-gcc10:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-10
          CXX: g++-10
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests
  gcc-build-ubuntu20-gcc9:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-9
          CXX: g++-9
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests

  # Ubuntu-20 Clang
  clang-build-ubuntu20-clang11:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang-11
          CXX: clang++-11
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests
  clang-build-ubuntu20-clang10:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang-10
          CXX: clang++-10
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests
  clang-build-ubuntu20-clang9:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang-9
          CXX: clang++-9
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests

  # Ubuntu-18 GCC
  gcc-build-ubuntu18-gcc10:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-10
          CXX: g++-10
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests
  gcc-build-ubuntu18-gcc9:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-9
          CXX: g++-9
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests

  # Ubuntu-18 Clang
  clang-build-ubuntu18-clang9:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang-9
          CXX: clang++-9
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests

  # MacOS-10.15 Clang
  clang-build-MacOS10-clang12:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: clang
          CXX: clang++
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests
  clang-build-MacOS10-clang11:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - run: |
          mkdir build && cd build
          comp="$(brew --prefix llvm)/bin/clang"
          export CC="${comp}"
          export CXX="${comp}++"
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests

  # MacOS-10.15 GCC
  clang-build-MacOS10-gcc10:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-10
          CXX: g++-10
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests
  clang-build-MacOS10-gcc9:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-9
          CXX: g++-9
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests
  clang-build-MacOS10-gcc8:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: recursive
      - env:
          CC: gcc-8
          CXX: g++-8
        run: |
          mkdir build && cd build
          cmake .. && make demos caterm.ui.tests caterm.unit.tests
          ./tests/caterm.unit.tests
